# Generated by Django 4.2.2 on 2023-06-16 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('policial', '0001_initial'),
        ('belico', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carga_Descarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.IntegerField(choices=[(1, 'CEL'), (2, 'TEN CEL'), (3, 'MAJ'), (4, 'CAP'), (5, 'TEN'), (6, 'ASP'), (7, 'SUB TEN'), (8, 'SGT'), (9, 'CB'), (10, 'SD'), (11, 'AL SD')], verbose_name='POSTO/GRADUAÇÃO')),
                ('nomeguerra', models.CharField(max_length=15, verbose_name='NOME DE GUERRA')),
                ('observacao', models.CharField(max_length=50, verbose_name='OBSERVAÇÃO')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('armamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belico.cadastroarma', verbose_name='ARMA')),
                ('cad_matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policial.cadastropolicial', verbose_name='MATRÍCULA')),
                ('carreg_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belico.cadastrocarregadores', verbose_name='CARREGADOR 1')),
                ('e_mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policial.cadastroemail', verbose_name='E-MAIL')),
                ('placabalistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='belico.cadastrocolete', verbose_name='COLETE')),
                ('senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policial.cadastrosenha', verbose_name='SENHA')),
            ],
            options={
                'verbose_name': 'Carga_Descarga',
                'verbose_name_plural': 'Cargas_Descargas',
            },
        ),
    ]
