# Generated by Django 4.2.2 on 2023-06-16 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cargadescarga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carga_descarga',
            name='senha',
            field=models.CharField(max_length=150, verbose_name='SENHA'),
        ),
    ]
