# Generated by Django 4.2.2 on 2023-06-16 01:28

from django.db import migrations, models
import policial.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CadastroEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50, verbose_name='E-MAIL')),
                ('primeiro_nome', models.CharField(max_length=20, verbose_name='Primeiro nome')),
            ],
            options={
                'verbose_name': 'E-mail',
                'verbose_name_plural': 'E-mails',
            },
        ),
        migrations.CreateModel(
            name='CadastroPolicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8, validators=[policial.models.validate_matricula], verbose_name='MATRÍCULA')),
                ('nome', models.CharField(max_length=50, verbose_name='NOME COMPLETO')),
            ],
            options={
                'verbose_name': 'Registro',
                'verbose_name_plural': 'Registros',
            },
        ),
        migrations.CreateModel(
            name='CadastroSenha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_name', models.CharField(max_length=50, verbose_name='NOME DE GUERRA')),
                ('s_password', models.CharField(max_length=30, verbose_name='SENHA')),
            ],
            options={
                'verbose_name': 'Acesso',
                'verbose_name_plural': 'Acessos',
            },
        ),
    ]
