# Generated by Django 4.2.2 on 2023-06-16 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrosenha',
            name='s_password',
            field=models.CharField(max_length=150, verbose_name='SENHA'),
        ),
    ]
